services:
  - type: web
    name: hornettrack
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn web.wsgi:application --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
